/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-26 08:20:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.semi.member.model.vo.Member;
import com.semi.member.model.vo.Member;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/member/../common/header.jsp", Long.valueOf(1682494118260L));
    _jspx_dependants.put("/views/member/../common/footer.jsp", Long.valueOf(1681981276000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.semi.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <style>\r\n");
      out.write("        *{\r\n");
      out.write("       	font-size:13px;\r\n");
      out.write("       	font-weight:400px;\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        html,body{\r\n");
      out.write("        box-sizing:border-box;\r\n");
      out.write("        overflow:auto;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        *:focus{\r\n");
      out.write("        outline: 2px solid  rgb(11, 95, 221);\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("	.outer{\r\n");
      out.write("/* 	//line-height: 1.5em; */\r\n");
      out.write("        width: 1400px;\r\n");
      out.write("        /* border: 3px solid darkgray; */\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        padding: 0 20px;\r\n");
      out.write("         margin-bottom: 20px; */\r\n");
      out.write("        height: 95%;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.loginBox{\r\n");
      out.write("        padding-top: 30px;\r\n");
      out.write("        padding-bottom: 20px;\r\n");
      out.write("        width: 900px;\r\n");
      out.write("        margin: 30px auto;\r\n");
      out.write("        border: 3px solid #2c7dc9;\r\n");
      out.write("        border-radius: 50px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;   \r\n");
      out.write("        align-items: center;\r\n");
      out.write("        /* justify-content: center; */\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        /* vertical-align: top; */\r\n");
      out.write("    }\r\n");
      out.write("   .outer button:not([type=submit]){\r\n");
      out.write("        /* margin: auto; */\r\n");
      out.write("        /* flex: 1; */\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        margin-bottom: 16px;\r\n");
      out.write("        width: 500px;\r\n");
      out.write("        /* font-size: x-large; */\r\n");
      out.write("        border-radius:30px;\r\n");
      out.write("    }\r\n");
      out.write("    .loginBox>input{\r\n");
      out.write("        width: 500px;\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        margin-bottom: 16px;\r\n");
      out.write("        margin-top: 0;\r\n");
      out.write("        border-radius:30px;\r\n");
      out.write("    }\r\n");
      out.write("     a{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #222;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #memberPwd{\r\n");
      out.write("    background:url(./images/images2/icon-01.png) no-repeat center right 15px;\r\n");
      out.write("    background-size: 20px;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("	\r\n");
      out.write("	.foot{\r\n");
      out.write("        padding: 50px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding-top: 8px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .outer .btn{\r\n");
      out.write("     border-radius : 35px;\r\n");
      out.write("     font-size:large;\r\n");
      out.write("     font-weight : 400px;\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    <title>회원가입</title>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

	///SemiProject 
	String contextPath = request.getContextPath();
	
	//로그인 유저 정보 꺼내오기
	Member loginUser = (Member)session.getAttribute("loginUser");
	//로그인 되어있다면 해당 유저정보가 담긴 Member객체가 반환 
	//로그인 되어있지 않으면 null (attribute에 loginUser라는 키값에 해당하는 데이터가 없으니)
	//알림 메세지도 꺼내주기
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("    <!-- 제이쿼리 -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.4.js\" integrity=\"sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Document</title>\r\n");
      out.write("        <style>\r\n");
      out.write("        html,body{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        div{\r\n");
      out.write("            /* border: 1px solid black; */\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        /*----------------------------로고--------------------------*/\r\n");
      out.write("        #header{\r\n");
      out.write("            width: 1420px;\r\n");
      out.write("            height: 170px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        #header_1{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 65%;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        #header_2{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 35%;\r\n");
      out.write("            border-top-style: solid; /*메뉴바 상 선*/\r\n");
      out.write("            border-top-width: 1px;\r\n");
      out.write("            border-top-color: rgb(148, 146, 146);\r\n");
      out.write("            border-bottom-style: solid; /*메뉴바 하 선*/\r\n");
      out.write("            border-bottom-width: 1px;\r\n");
      out.write("            border-bottom-color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        #header_1>div{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        #logo{\r\n");
      out.write("            width: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        #login{\r\n");
      out.write("            width: 30%;\r\n");
      out.write("        }\r\n");
      out.write("        #logo_img{\r\n");
      out.write("            height: 65px;\r\n");
      out.write("            width: 230px;\r\n");
      out.write("            position: absolute; /*로고 이미지 중간으로 위치 잡기*/\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            top: 0px;\r\n");
      out.write("            bottom: 0px;\r\n");
      out.write("            left: 550px;\r\n");
      out.write("        }\r\n");
      out.write("        /*--------------------------로그인 버튼----------------------*/\r\n");
      out.write("        #login>a{\r\n");
      out.write("            color: rgb(148, 146, 146);\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            margin: 6px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            top: 84px;\r\n");
      out.write("            left: 190px;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        /*------------------------메뉴바------------------------------*/\r\n");
      out.write("        #header_2>div{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        #category_all{\r\n");
      out.write("            width: 23%;\r\n");
      out.write("        }\r\n");
      out.write("        #category_area{\r\n");
      out.write("            width: 43%;\r\n");
      out.write("        }\r\n");
      out.write("        #search_form_area{\r\n");
      out.write("            width: 34%;\r\n");
      out.write("        }\r\n");
      out.write("        #header_2 li{\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("        }\r\n");
      out.write("        #header_2 a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_1_text{\r\n");
      out.write("            cursor:default;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_1{ /*ul의 기본 마진,패딩 없애기*/\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_1>li{ /*li영역 먼저 잡아주기*/\r\n");
      out.write("            float: right;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 63%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_1 a{ /*태그 크기 li에 맞춰주기*/\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            line-height: 58px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            background-color: rgb(33, 6, 106);\r\n");
      out.write("            color: rgb(237, 231, 231);\r\n");
      out.write("        }\r\n");
      out.write("        #ca_1 a:hover{\r\n");
      out.write("            background-color: rgb(58, 40, 100);\r\n");
      out.write("        }\r\n");
      out.write("        #ca_2{\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_2>li{ /*li영역 먼저 잡아주기*/\r\n");
      out.write("            /* left: 2%; */\r\n");
      out.write("            float:left;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 23%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            position: relative; /*위치 옮기기*/\r\n");
      out.write("            left: 19px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #ca_2 a{ /*태그 크기 li에 맞춰주기*/\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            line-height: 58px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            /* background-color: rgb(33, 6, 106); */\r\n");
      out.write("            color: rgb(65, 61, 61);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #ca_2 a:hover,#all_list a:hover{\r\n");
      out.write("            background-color: rgb(227, 225, 230);\r\n");
      out.write("        }\r\n");
      out.write("        /*안보이게하기=====================================*/\r\n");
      out.write("        #customer_li,#book_li,#all_list{\r\n");
      out.write("       	 	background-color: rgb(255, 255, 255);\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("        }\r\n");
      out.write("        #customer_li a,#book_li a{\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: rgb(104, 101, 101);\r\n");
      out.write("        }\r\n");
      out.write("        #all_list a{\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            color: rgb(46, 43, 43);\r\n");
      out.write("        }\r\n");
      out.write("        #ca_2>li>ul,#ca_1>li>ul{/*안보이게하기 1단계*/\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_2>li>a:hover+ul,#ca_1>li>a:hover+ul{/*안보이게하기 2단계*/\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_2>li>ul:hover,#ca_1>li>ul:hover{/*안보이게하기 3단계*/\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        #book_li,#customer_li,#all_list{\r\n");
      out.write("            border-top-style: solid; /*메뉴바 하 선*/\r\n");
      out.write("            border-top-width: 1px;\r\n");
      out.write("            border-top-color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        #book_li li{\r\n");
      out.write("        	background-color: white;\r\n");
      out.write("        	position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        #all_list li{\r\n");
      out.write("        	position: relative;\r\n");
      out.write("        	z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        #all_list_1 a,#customer_1 a{\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            line-height: 2;\r\n");
      out.write("            /* background-color: aqua; */\r\n");
      out.write("           \r\n");
      out.write("        }\r\n");
      out.write("        #all_list_1>li,#customer_1>li{\r\n");
      out.write("            /*border: 1px solid red;*/\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("        }\r\n");
      out.write("        #all_list_1,#customer_1{\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            width: 58%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: right;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            /* background-color: white; */\r\n");
      out.write("        }\r\n");
      out.write("        #all_list_1 a:hover{\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #customer_1 a:hover{\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("        /*--------------------검색창--------------------------*/\r\n");
      out.write("        #search_form_area form{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("        }\r\n");
      out.write("        #search_form>*{\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        #search_text{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-left-style: solid; /*검색 좌 선*/\r\n");
      out.write("            border-left-width: 1px;\r\n");
      out.write("            border-left-color: rgb(148, 146, 146);\r\n");
      out.write("            /*background:url(resources/돋보기.png) no-repeat center right 15px;*/\r\n");
      out.write("    		background-size: 20px;\r\n");
      out.write("    		background-color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        #search_btn{\r\n");
      out.write("            width: 20%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: rgb(148, 146, 146);\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-right-style: solid; /*검색 우 선*/\r\n");
      out.write("            border-right-width: 1px;\r\n");
      out.write("            border-right-color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        input:focus{ /*클릭시 테두리*/\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        /*-----------------콘텐츠------------------------*/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        /*베스트-----------------------------------------------------*/\r\n");
      out.write("        #best>p{\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 25%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            font-size: 40px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            line-height: 100px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #best>div{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 75%;\r\n");
      out.write("            border-top-style: solid; /*검색 우 선*/\r\n");
      out.write("            border-top-width: 3px;\r\n");
      out.write("            border-top-color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"header_1\">\r\n");
      out.write("                <div id=\"logo\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("\">\r\n");
      out.write("                        <img src=\"resources/사이트이름.png\" alt=\"\" id=\"logo_img\"><!--클릭시 메인페이지-->\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                ");
if(loginUser == null) {
      out.write("\r\n");
      out.write("                <div id=\"login\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/logform.me\" id=\"login_btn\">로그인</a>\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/enrollForm.me\" id=\"mem_btn\">회원가입</a>\r\n");
      out.write("                </div>\r\n");
      out.write("             \r\n");
      out.write("                ");
}else if(loginUser != null){ 
      out.write("\r\n");
      out.write("                <div id=\"login_mem\" style=\"background-color: blueviolet;\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/myPage.me\" id=\"login_btn\">마이페이지</a>\r\n");
      out.write("                    <a href=\"\" id=\"mem_btn\">장바구니</a>\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/logout.me\" id=\"mem_btn\">로그아웃</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                 ");
} 
      out.write("\r\n");
      out.write("                 <!--  ");
//}else{ 
      out.write("\r\n");
      out.write("	                <div id=\"login_mem\">\r\n");
      out.write("	                    <a href=\"\" id=\"login_btn\">관리페이지</a>\r\n");
      out.write("	                    <a href=\"");
//=contextPath 
      out.write("/logout.me\" id=\"mem_btn\">로그아웃</a>\r\n");
      out.write("	                </div>\r\n");
      out.write("               ");
//} 
      out.write("  -->\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"header_2\">\r\n");
      out.write("                <div id=\"category_all\">\r\n");
      out.write("                    <ul id=\"ca_1\">\r\n");
      out.write("                    \r\n");
      out.write("                        <li><a id=\"ca_1_text\">&#8801; 전체 카테고리</a>\r\n");
      out.write("                            <ul id=\"all_list\">\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/book.list?currentPage=1\">도서</a>\r\n");
      out.write("                                    <ul id=\"all_list_1\">\r\n");
      out.write("                                        <li><a href=\"");
      out.print(contextPath );
      out.write("/book.be?currentPage=1\" style=\"float: right; width: 206px; text-align:center;\">베스트 셀러</a></li>\r\n");
      out.write("                                        <li><a href=\"");
      out.print(contextPath );
      out.write("/book.new?currentPage=1\" style=\"float: right; width: 206px; text-align:center;\">신간 도서</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath);
      out.write("/item.list?currentPage=1\">쇼핑</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/attendance.v\"\">출석체크</a></li>\r\n");
      out.write("                                <li><a href=\"\">고객센터</a>\r\n");
      out.write("                                    <ul id=\"customer_1\">\r\n");
      out.write("                                        <li><a href=\"\" style=\"float: right; width: 206px; text-align:center;\">공지사항</a></li>\r\n");
      out.write("                                        <li><a href=\"\" style=\"float: right; width: 206px; text-align:center;\">자주묻는 질문</a></li>\r\n");
      out.write("                                        <li><a href=\"\" style=\"float: right; width: 206px; text-align:center;\">1:1 문의</a></li>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"category_area\">\r\n");
      out.write("                    <ul id=\"ca_2\">\r\n");
      out.write("                        <li id=\"book\"><a href=\"");
      out.print(contextPath );
      out.write("/book.list?currentPage=1\">도서</a>\r\n");
      out.write("                            <ul id=\"book_li\">\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath);
      out.write("/book.be?currentPage=1\">베스트 도서</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/book.new?currentPage=1\">신간 도서</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(contextPath);
      out.write("/item.list?currentPage=1\">쇼핑</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(contextPath );
      out.write("/attendance.v\">출석체크</a></li>\r\n");
      out.write("                        <li id=\"customer\"><a href=\"\">고객센터</a>\r\n");
      out.write("                            <ul id=\"customer_li\">\r\n");
      out.write("                                <li><a href=\"\">공지사항</a></li>\r\n");
      out.write("                                <li><a href=\"\">자주묻는 질문</a></li>\r\n");
      out.write("                                <li><a href=\"\">1:1 문의</a></li>\r\n");
      out.write("                                \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"search_form_area\">\r\n");
      out.write("                    <form action=\"test.do\" id=\"search_form\">\r\n");
      out.write("                        <input type=\"search\" id=\"search_text\" placeholder=\"도서, 상품 검색\">\r\n");
      out.write("                        <button type=\"submit\" id=\"search_btn\">\r\n");
      out.write("                        <img src=\"resources/돋보기.png\" width=\"20px\" height=\"20px\" alt=\"\" style=\"position: relative; left: 2px; top: 4px;\">\r\n");
      out.write("                        	검색</button> <!--검색창에 보내기-->\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <div class=\"outer\">\r\n");
      out.write("	\r\n");
      out.write("        <form action=\"");
      out.print(contextPath);
      out.write("/login.me\" method=\"post\">\r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("          <div class=\"loginBox\">\r\n");
      out.write("            <input type=\"text\" name=\"memberId\" placeholder=\"아이디를 입력해주세요\">\r\n");
      out.write("            <input type=\"password\" name=\"memberPwd\" id=\"memberPwd\" placeholder=\"비밀번호를 입력해주세요\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\" id=\"loginBtn\"  style=\"padding:20px; margin-bottom: 16px; width: 500px;\">로그인</button>\r\n");
      out.write("            <a href=\"");
      out.print(contextPath);
      out.write("/searchid.me\">아이디 </a> / <a href=\"");
      out.print(contextPath);
      out.write("/searchpwd.me\"> 비밀번호 찾기</a> \r\n");
      out.write("          </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"foot\">\r\n");
      out.write("\r\n");
      out.write("              <button type=\"button\" class =\"btn btn-outline-primary\" style=\"padding: 12px; \" onclick=\"enrollPage();\">회원가입</button>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              <button class=\"btn btn-outline-secondary\" style=\"padding: 12px;\">비회원 주문 조회</button>\r\n");
      out.write("              \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </form>    \r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("    function enrollPage(){\r\n");
      out.write("		//location.href = \"");
      out.print(contextPath);
      out.write("/semiViews/member/memberEnrollForm.jsp\";\r\n");
      out.write("		//웹 애플리케이션의 디렉토리 구조가 그대로 url에 노출되어 보안에 취약해진다.\r\n");
      out.write("		//단순 페이지 이동이여도 servlet을 거쳐서 매핑값이 노출되어 갈수있도록 작업하기.\r\n");
      out.write("		\r\n");
      out.write("		location.href =\"");
      out.print(contextPath);
      out.write("/enrollForm.me\";\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("    </script>\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Document</title>\r\n");
      out.write("        <style>\r\n");
      out.write("        /*푸터===================================================================*/\r\n");
      out.write("        div{\r\n");
      out.write("            /*border: 1px solid black;*/\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        #footer{\r\n");
      out.write("            width: 1420px;\r\n");
      out.write("            height: 150px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            border-top-style: solid; /*푸터 상 선*/\r\n");
      out.write("            border-top-width: 1px;\r\n");
      out.write("            border-top-color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        #footer>div{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        #f_1{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 40%;\r\n");
      out.write("        }\r\n");
      out.write("        #f_2{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 60%;\r\n");
      out.write("        }\r\n");
      out.write("        #f_1>a{\r\n");
      out.write("            margin: 8px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            left: 100px;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        #f_2>p{\r\n");
      out.write("            color: rgb(127, 121, 122);\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            left: 120px;\r\n");
      out.write("        }       \r\n");
      out.write("        #f_1_logo{\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            width: 130px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            top: 7px;\r\n");
      out.write("        }\r\n");
      out.write("        a:hover{\r\n");
      out.write("        	outline : \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("            <div id=\"f_1\">\r\n");
      out.write("                <a href=\"\" ><img id=\"f_1_logo\" src=\"resources/사이트이름.png\" alt=\"logo\"> </a> <!--메인사이트로-->\r\n");
      out.write("                <a href=\"\" >이용약관</a>\r\n");
      out.write("                <a href=\"\" >개인정보처리방침</a>\r\n");
      out.write("                <a href=\"\" >청소년보호정책</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"f_2\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    대표이사 : 읽어조 | 서울특별시 종로구 종로1 | 사업자 등록 번호 : 111-22-33333\r\n");
      out.write("                    <br>\r\n");
      out.write("                    대표전화 : 1111-1111 | FAX : 0505-987-6543\r\n");
      out.write("                </p>\r\n");
      out.write("                <p> kh © book center</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
