/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-26 01:47:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.semi.member.model.vo.Member;

public final class map_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/../common/header.jsp", Long.valueOf(1682471531229L));
    _jspx_dependants.put("/views/common/../common/footer.jsp", Long.valueOf(1682471531228L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.semi.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>키워드로 장소검색하고 목록으로 표출하기</title>\r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("    body{\r\n");
      out.write("    margin:0;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write(".map_wrap, .map_wrap * {margin:0;padding:0;font-family:'Malgun Gothic',dotum,'돋움',sans-serif;font-size:12px;}\r\n");
      out.write(".map_wrap a, .map_wrap a:hover, .map_wrap a:active{color:#000;text-decoration: none;}\r\n");
      out.write(".map_wrap {position:relative;width:100%;height:500px; overflow:auto; }\r\n");
      out.write("#menu_wrap {position:absolute;top:0; left:0;bottom:0;width:250px;margin:10px 0 30px 10px;padding:5px;overflow-y:auto;background:rgba(255, 255, 255, 0.7);z-index: 1;font-size:12px;border-radius: 10px;}\r\n");
      out.write(".bg_white {background:#fff; opacity:2; }\r\n");
      out.write("#menu_wrap hr {display: block; height: 1px;border: 0; border-top: 2px solid #5F5F5F;margin:3px 0;}\r\n");
      out.write("#menu_wrap .option{text-align: center;}\r\n");
      out.write("#menu_wrap .option p {margin:10px 0;}  \r\n");
      out.write("#menu_wrap .option button {margin-left:5px;}\r\n");
      out.write("#placesList li {list-style: none;}\r\n");
      out.write("#placesList .item {position:relative;border-bottom:1px solid #888;overflow: hidden;cursor: pointer;min-height: 65px;}\r\n");
      out.write("#placesList .item span {display: block;margin-top:4px;}\r\n");
      out.write("#placesList .item h5, #placesList .item .info {text-overflow: ellipsis;overflow: hidden;white-space: nowrap;}\r\n");
      out.write("#placesList .item .info{padding:10px 0 10px 55px;}\r\n");
      out.write("#placesList .info .gray {color:#8a8a8a;}\r\n");
      out.write("#placesList .info .jibun {padding-left:26px;background:url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/places_jibun.png) no-repeat;}\r\n");
      out.write("#placesList .info .tel {color:#009900;}\r\n");
      out.write("#placesList .item .markerbg {float:left;position:absolute;width:36px; height:37px;margin:10px 0 0 10px;background:url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png) no-repeat;}\r\n");
      out.write("#placesList .item .marker_1 {background-position: 0 -10px;}\r\n");
      out.write("#placesList .item .marker_2 {background-position: 0 -56px;}\r\n");
      out.write("#placesList .item .marker_3 {background-position: 0 -102px}\r\n");
      out.write("#placesList .item .marker_4 {background-position: 0 -148px;}\r\n");
      out.write("#placesList .item .marker_5 {background-position: 0 -194px;}\r\n");
      out.write("#placesList .item .marker_6 {background-position: 0 -240px;}\r\n");
      out.write("#placesList .item .marker_7 {background-position: 0 -286px;}\r\n");
      out.write("#placesList .item .marker_8 {background-position: 0 -332px;}\r\n");
      out.write("#placesList .item .marker_9 {background-position: 0 -378px;}\r\n");
      out.write("#placesList .item .marker_10 {background-position: 0 -423px;}\r\n");
      out.write("#placesList .item .marker_11 {background-position: 0 -470px;}\r\n");
      out.write("#placesList .item .marker_12 {background-position: 0 -516px;}\r\n");
      out.write("#placesList .item .marker_13 {background-position: 0 -562px;}\r\n");
      out.write("#placesList .item .marker_14 {background-position: 0 -608px;}\r\n");
      out.write("#placesList .item .marker_15 {background-position: 0 -654px;}\r\n");
      out.write("#pagination {margin:10px auto;text-align: center;}\r\n");
      out.write("#pagination a {display:inline-block;margin-right:10px;}\r\n");
      out.write("#pagination .on {font-weight: bold; cursor: default;color:#777;}\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	///SemiProject 
	String contextPath = request.getContextPath();
	
	//로그인 유저 정보 꺼내오기
	Member loginUser = (Member)session.getAttribute("loginUser");
	//로그인 되어있다면 해당 유저정보가 담긴 Member객체가 반환 
	//로그인 되어있지 않으면 null (attribute에 loginUser라는 키값에 해당하는 데이터가 없으니)
	//알림 메세지도 꺼내주기
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("    <!-- 제이쿼리 -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.4.js\" integrity=\"sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Document</title>\r\n");
      out.write("        <style>\r\n");
      out.write("        html,body{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        div{\r\n");
      out.write("            /* border: 1px solid black; */\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        /*----------------------------로고--------------------------*/\r\n");
      out.write("        #header{\r\n");
      out.write("            width: 1420px;\r\n");
      out.write("            height: 170px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        #header_1{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 65%;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        #header_2{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 35%;\r\n");
      out.write("            border-top-style: solid; /*메뉴바 상 선*/\r\n");
      out.write("            border-top-width: 1px;\r\n");
      out.write("            border-top-color: rgb(148, 146, 146);\r\n");
      out.write("            border-bottom-style: solid; /*메뉴바 하 선*/\r\n");
      out.write("            border-bottom-width: 1px;\r\n");
      out.write("            border-bottom-color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        #header_1>div{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        #logo{\r\n");
      out.write("            width: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        #login{\r\n");
      out.write("            width: 30%;\r\n");
      out.write("        }\r\n");
      out.write("        #logo_img{\r\n");
      out.write("            height: 65px;\r\n");
      out.write("            width: 230px;\r\n");
      out.write("            position: absolute; /*로고 이미지 중간으로 위치 잡기*/\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            top: 0px;\r\n");
      out.write("            bottom: 0px;\r\n");
      out.write("            left: 550px;\r\n");
      out.write("        }\r\n");
      out.write("        /*--------------------------로그인 버튼----------------------*/\r\n");
      out.write("        #login>a{\r\n");
      out.write("            color: rgb(148, 146, 146);\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            margin: 6px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            top: 84px;\r\n");
      out.write("            left: 190px;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        /*------------------------메뉴바------------------------------*/\r\n");
      out.write("        #header_2>div{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        #category_all{\r\n");
      out.write("            width: 23%;\r\n");
      out.write("        }\r\n");
      out.write("        #category_area{\r\n");
      out.write("            width: 43%;\r\n");
      out.write("        }\r\n");
      out.write("        #search_form_area{\r\n");
      out.write("            width: 34%;\r\n");
      out.write("        }\r\n");
      out.write("        #header_2 li{\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("        }\r\n");
      out.write("        #header_2 a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_1_text{\r\n");
      out.write("            cursor:default;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_1{ /*ul의 기본 마진,패딩 없애기*/\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_1>li{ /*li영역 먼저 잡아주기*/\r\n");
      out.write("            float: right;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 63%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_1 a{ /*태그 크기 li에 맞춰주기*/\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            line-height: 58px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            background-color: rgb(33, 6, 106);\r\n");
      out.write("            color: rgb(237, 231, 231);\r\n");
      out.write("        }\r\n");
      out.write("        #ca_1 a:hover{\r\n");
      out.write("            background-color: rgb(58, 40, 100);\r\n");
      out.write("        }\r\n");
      out.write("        #ca_2{\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_2>li{ /*li영역 먼저 잡아주기*/\r\n");
      out.write("            /* left: 2%; */\r\n");
      out.write("            float:left;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 23%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            position: relative; /*위치 옮기기*/\r\n");
      out.write("            left: 19px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #ca_2 a{ /*태그 크기 li에 맞춰주기*/\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            line-height: 58px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            /* background-color: rgb(33, 6, 106); */\r\n");
      out.write("            color: rgb(65, 61, 61);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #ca_2 a:hover,#all_list a:hover{\r\n");
      out.write("            background-color: rgb(227, 225, 230);\r\n");
      out.write("        }\r\n");
      out.write("        /*안보이게하기=====================================*/\r\n");
      out.write("        #customer_li,#book_li,#all_list{\r\n");
      out.write("       	 	background-color: rgb(255, 255, 255);\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("        }\r\n");
      out.write("        #customer_li a,#book_li a{\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: rgb(104, 101, 101);\r\n");
      out.write("        }\r\n");
      out.write("        #all_list a{\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            color: rgb(46, 43, 43);\r\n");
      out.write("        }\r\n");
      out.write("        #ca_2>li>ul,#ca_1>li>ul{/*안보이게하기 1단계*/\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_2>li>a:hover+ul,#ca_1>li>a:hover+ul{/*안보이게하기 2단계*/\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        #ca_2>li>ul:hover,#ca_1>li>ul:hover{/*안보이게하기 3단계*/\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        #book_li,#customer_li,#all_list{\r\n");
      out.write("            border-top-style: solid; /*메뉴바 하 선*/\r\n");
      out.write("            border-top-width: 1px;\r\n");
      out.write("            border-top-color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        #book_li li{\r\n");
      out.write("        	background-color: white;\r\n");
      out.write("        	position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        #all_list li{\r\n");
      out.write("        	position: relative;\r\n");
      out.write("        	z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        #all_list_1 a,#customer_1 a{\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            line-height: 2;\r\n");
      out.write("            /* background-color: aqua; */\r\n");
      out.write("        }\r\n");
      out.write("        #all_list_1>li,#customer_1>li{\r\n");
      out.write("            /* border: 1px solid red; */\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("        }\r\n");
      out.write("        #all_list_1,#customer_1{\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            width: 58%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: right;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            /* background-color: white; */\r\n");
      out.write("        }\r\n");
      out.write("        #all_list_1 a:hover{\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("        #customer_1 a:hover{\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("        /*--------------------검색창--------------------------*/\r\n");
      out.write("        #search_form_area form{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("        }\r\n");
      out.write("        #search_form>*{\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        #search_text{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-left-style: solid; /*검색 좌 선*/\r\n");
      out.write("            border-left-width: 1px;\r\n");
      out.write("            border-left-color: rgb(148, 146, 146);\r\n");
      out.write("            /*background:url(resources/돋보기.png) no-repeat center right 15px;*/\r\n");
      out.write("    		background-size: 20px;\r\n");
      out.write("    		background-color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        #search_btn{\r\n");
      out.write("            width: 20%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: rgb(148, 146, 146);\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-right-style: solid; /*검색 우 선*/\r\n");
      out.write("            border-right-width: 1px;\r\n");
      out.write("            border-right-color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        input:focus{ /*클릭시 테두리*/\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        /*-----------------콘텐츠------------------------*/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        /*베스트-----------------------------------------------------*/\r\n");
      out.write("        #best>p{\r\n");
      out.write("            margin: 0px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 25%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            font-size: 40px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            line-height: 100px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #best>div{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 75%;\r\n");
      out.write("            border-top-style: solid; /*검색 우 선*/\r\n");
      out.write("            border-top-width: 3px;\r\n");
      out.write("            border-top-color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"header_1\">\r\n");
      out.write("                <div id=\"logo\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("\">\r\n");
      out.write("                        <img src=\"resources/사이트이름.png\" alt=\"\" id=\"logo_img\"><!--클릭시 메인페이지-->\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                ");
if(loginUser == null) {
      out.write("\r\n");
      out.write("                <div id=\"login\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/logform.me\" id=\"login_btn\">로그인</a>\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/enrollForm.me\" id=\"mem_btn\">회원가입</a>\r\n");
      out.write("                </div>\r\n");
      out.write("             \r\n");
      out.write("                ");
}else if(loginUser != null){ 
      out.write("\r\n");
      out.write("                <div id=\"login_mem\" style=\"background-color: blueviolet;\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/myPage.me\" id=\"login_btn\">마이페이지</a>\r\n");
      out.write("                    <a href=\"\" id=\"mem_btn\">장바구니</a>\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/logout.me\" id=\"mem_btn\">로그아웃</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                 ");
} 
      out.write("\r\n");
      out.write("                 <!--  ");
//}else{ 
      out.write("\r\n");
      out.write("	                <div id=\"login_mem\">\r\n");
      out.write("	                    <a href=\"\" id=\"login_btn\">관리페이지</a>\r\n");
      out.write("	                    <a href=\"");
//=contextPath 
      out.write("/logout.me\" id=\"mem_btn\">로그아웃</a>\r\n");
      out.write("	                </div>\r\n");
      out.write("               ");
//} 
      out.write("  -->\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"header_2\">\r\n");
      out.write("                <div id=\"category_all\">\r\n");
      out.write("                    <ul id=\"ca_1\">\r\n");
      out.write("                    \r\n");
      out.write("                        <li><a id=\"ca_1_text\">&#8801; 전체 카테고리</a>\r\n");
      out.write("                            <ul id=\"all_list\">\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/book.list?currentPage=1\">도서</a>\r\n");
      out.write("                                    <ul id=\"all_list_1\">\r\n");
      out.write("                                        <li><a href=\"\" style=\"float: right; width: 206px; text-align:center;\">베스트 셀러</a></li>\r\n");
      out.write("                                        <li><a href=\"");
      out.print(contextPath );
      out.write("/book.new?currentPage=1\"\" style=\"float: right; width: 206px; text-align:center;\">신간 도서</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath);
      out.write("/item.list?currentPage=1\">쇼핑</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/attendance.v\"\">출석체크</a></li>\r\n");
      out.write("                                <li><a href=\"\">고객센터</a>\r\n");
      out.write("                                    <ul id=\"customer_1\">\r\n");
      out.write("                                        <li><a href=\"\" style=\"float: right; width: 206px; text-align:center;\">공지사항</a></li>\r\n");
      out.write("                                        <li><a href=\"\" style=\"float: right; width: 206px; text-align:center;\">자주묻는 질문</a></li>\r\n");
      out.write("                                        <li><a href=\"\" style=\"float: right; width: 206px; text-align:center;\">1:1 문의</a></li>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"category_area\">\r\n");
      out.write("                    <ul id=\"ca_2\">\r\n");
      out.write("                        <li id=\"book\"><a href=\"");
      out.print(contextPath );
      out.write("/book.list?currentPage=1\">도서</a>\r\n");
      out.write("                            <ul id=\"book_li\">\r\n");
      out.write("                                <li><a href=\"\">베스트 도서</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/book.new?currentPage=1\"\">신간 도서</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(contextPath);
      out.write("/item.list?currentPage=1\">쇼핑</a></li>\r\n");
      out.write("                        <li><a href=\"");
      out.print(contextPath );
      out.write("/attendance.v\">출석체크</a></li>\r\n");
      out.write("                        <li id=\"customer\"><a href=\"\">고객센터</a>\r\n");
      out.write("                            <ul id=\"customer_li\">\r\n");
      out.write("                                <li><a href=\"\">공지사항</a></li>\r\n");
      out.write("                                <li><a href=\"\">자주묻는 질문</a></li>\r\n");
      out.write("                                <li><a href=\"\">1:1 문의</a></li>\r\n");
      out.write("                                \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"search_form_area\">\r\n");
      out.write("                    <form action=\"test.do\" id=\"search_form\">\r\n");
      out.write("                        <input type=\"search\" id=\"search_text\" placeholder=\"도서, 상품 검색\">\r\n");
      out.write("                        <button type=\"submit\" id=\"search_btn\">\r\n");
      out.write("                        <img src=\"resources/돋보기.png\" width=\"20px\" height=\"20px\" alt=\"\" style=\"position: relative; left: 2px; top: 4px;\">\r\n");
      out.write("                        	검색</button> <!--검색창에 보내기-->\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"map_wrap\">\r\n");
      out.write("    <div id=\"map\" style=\"width:100%;height:100%;position:relative;overflow:hidden;\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"menu_wrap\" class=\"bg_white\">\r\n");
      out.write("        <div class=\"option\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <form onsubmit=\"searchPlaces(); return false;\">\r\n");
      out.write("                    키워드 : <input type=\"text\" value=\"이태원 맛집\" id=\"keyword\" size=\"15\"> \r\n");
      out.write("                    <button type=\"submit\">검색하기</button> \r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <ul id=\"placesList\"></ul>\r\n");
      out.write("        <div id=\"pagination\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Document</title>\r\n");
      out.write("        <style>\r\n");
      out.write("        /*푸터===================================================================*/\r\n");
      out.write("        div{\r\n");
      out.write("            /*border: 1px solid black;*/\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        #footer{\r\n");
      out.write("            width: 1420px;\r\n");
      out.write("            height: 150px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            border-top-style: solid; /*푸터 상 선*/\r\n");
      out.write("            border-top-width: 1px;\r\n");
      out.write("            border-top-color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        #footer>div{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        #f_1{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 40%;\r\n");
      out.write("        }\r\n");
      out.write("        #f_2{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 60%;\r\n");
      out.write("        }\r\n");
      out.write("        #f_1>a{\r\n");
      out.write("            margin: 8px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            left: 100px;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: rgb(148, 146, 146);\r\n");
      out.write("        }\r\n");
      out.write("        #f_2>p{\r\n");
      out.write("            color: rgb(127, 121, 122);\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            left: 120px;\r\n");
      out.write("        }       \r\n");
      out.write("        #f_1_logo{\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            width: 130px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            top: 7px;\r\n");
      out.write("        }\r\n");
      out.write("        a:hover{\r\n");
      out.write("        	outline : \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("            <div id=\"f_1\">\r\n");
      out.write("                <a href=\"\" ><img id=\"f_1_logo\" src=\"resources/사이트이름.png\" alt=\"logo\"> </a> <!--메인사이트로-->\r\n");
      out.write("                <a href=\"\" >이용약관</a>\r\n");
      out.write("                <a href=\"\" >개인정보처리방침</a>\r\n");
      out.write("                <a href=\"\" >청소년보호정책</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"f_2\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    대표이사 : 읽어조 | 서울특별시 종로구 종로1 | 사업자 등록 번호 : 111-22-33333\r\n");
      out.write("                    <br>\r\n");
      out.write("                    대표전화 : 1111-1111 | FAX : 0505-987-6543\r\n");
      out.write("                </p>\r\n");
      out.write("                <p> kh © book center</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=774a7908df1b6d2a60aaa424fa0bbff7&libraries=services\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("// 마커를 담을 배열입니다\r\n");
      out.write("var markers = [];\r\n");
      out.write("\r\n");
      out.write("var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("    mapOption = {\r\n");
      out.write("        center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표\r\n");
      out.write("        level: 3 // 지도의 확대 레벨\r\n");
      out.write("    };  \r\n");
      out.write("\r\n");
      out.write("// 지도를 생성합니다    \r\n");
      out.write("var map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("\r\n");
      out.write("// 장소 검색 객체를 생성합니다\r\n");
      out.write("var ps = new kakao.maps.services.Places();  \r\n");
      out.write("\r\n");
      out.write("// 검색 결과 목록이나 마커를 클릭했을 때 장소명을 표출할 인포윈도우를 생성합니다\r\n");
      out.write("var infowindow = new kakao.maps.InfoWindow({zIndex:1});\r\n");
      out.write("\r\n");
      out.write("// 키워드로 장소를 검색합니다\r\n");
      out.write("searchPlaces();\r\n");
      out.write("\r\n");
      out.write("// 키워드 검색을 요청하는 함수입니다\r\n");
      out.write("function searchPlaces() {\r\n");
      out.write("\r\n");
      out.write("    var keyword = document.getElementById('keyword').value;\r\n");
      out.write("\r\n");
      out.write("    if (!keyword.replace(/^\\s+|\\s+$/g, '')) {\r\n");
      out.write("        alert('키워드를 입력해주세요!');\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 장소검색 객체를 통해 키워드로 장소검색을 요청합니다\r\n");
      out.write("    ps.keywordSearch( keyword, placesSearchCB); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 장소검색이 완료됐을 때 호출되는 콜백함수 입니다\r\n");
      out.write("function placesSearchCB(data, status, pagination) {\r\n");
      out.write("    if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("\r\n");
      out.write("        // 정상적으로 검색이 완료됐으면\r\n");
      out.write("        // 검색 목록과 마커를 표출합니다\r\n");
      out.write("        displayPlaces(data);\r\n");
      out.write("\r\n");
      out.write("        // 페이지 번호를 표출합니다\r\n");
      out.write("        displayPagination(pagination);\r\n");
      out.write("\r\n");
      out.write("    } else if (status === kakao.maps.services.Status.ZERO_RESULT) {\r\n");
      out.write("\r\n");
      out.write("        alert('검색 결과가 존재하지 않습니다.');\r\n");
      out.write("        return;\r\n");
      out.write("\r\n");
      out.write("    } else if (status === kakao.maps.services.Status.ERROR) {\r\n");
      out.write("\r\n");
      out.write("        alert('검색 결과 중 오류가 발생했습니다.');\r\n");
      out.write("        return;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 검색 결과 목록과 마커를 표출하는 함수입니다\r\n");
      out.write("function displayPlaces(places) {\r\n");
      out.write("\r\n");
      out.write("    var listEl = document.getElementById('placesList'), \r\n");
      out.write("    menuEl = document.getElementById('menu_wrap'),\r\n");
      out.write("    fragment = document.createDocumentFragment(), \r\n");
      out.write("    bounds = new kakao.maps.LatLngBounds(), \r\n");
      out.write("    listStr = '';\r\n");
      out.write("    \r\n");
      out.write("    // 검색 결과 목록에 추가된 항목들을 제거합니다\r\n");
      out.write("    removeAllChildNods(listEl);\r\n");
      out.write("\r\n");
      out.write("    // 지도에 표시되고 있는 마커를 제거합니다\r\n");
      out.write("    removeMarker();\r\n");
      out.write("    \r\n");
      out.write("    for ( var i=0; i<places.length; i++ ) {\r\n");
      out.write("\r\n");
      out.write("        // 마커를 생성하고 지도에 표시합니다\r\n");
      out.write("        var placePosition = new kakao.maps.LatLng(places[i].y, places[i].x),\r\n");
      out.write("            marker = addMarker(placePosition, i), \r\n");
      out.write("            itemEl = getListItem(i, places[i]); // 검색 결과 항목 Element를 생성합니다\r\n");
      out.write("\r\n");
      out.write("        // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해\r\n");
      out.write("        // LatLngBounds 객체에 좌표를 추가합니다\r\n");
      out.write("        bounds.extend(placePosition);\r\n");
      out.write("\r\n");
      out.write("        // 마커와 검색결과 항목에 mouseover 했을때\r\n");
      out.write("        // 해당 장소에 인포윈도우에 장소명을 표시합니다\r\n");
      out.write("        // mouseout 했을 때는 인포윈도우를 닫습니다\r\n");
      out.write("        (function(marker, title) {\r\n");
      out.write("            kakao.maps.event.addListener(marker, 'mouseover', function() {\r\n");
      out.write("                displayInfowindow(marker, title);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            kakao.maps.event.addListener(marker, 'mouseout', function() {\r\n");
      out.write("                infowindow.close();\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            itemEl.onmouseover =  function () {\r\n");
      out.write("                displayInfowindow(marker, title);\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            itemEl.onmouseout =  function () {\r\n");
      out.write("                infowindow.close();\r\n");
      out.write("            };\r\n");
      out.write("        })(marker, places[i].place_name);\r\n");
      out.write("\r\n");
      out.write("        fragment.appendChild(itemEl);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 검색결과 항목들을 검색결과 목록 Element에 추가합니다\r\n");
      out.write("    listEl.appendChild(fragment);\r\n");
      out.write("    menuEl.scrollTop = 0;\r\n");
      out.write("\r\n");
      out.write("    // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다\r\n");
      out.write("    map.setBounds(bounds);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 검색결과 항목을 Element로 반환하는 함수입니다\r\n");
      out.write("function getListItem(index, places) {\r\n");
      out.write("\r\n");
      out.write("    var el = document.createElement('li'),\r\n");
      out.write("    itemStr = '<span class=\"markerbg marker_' + (index+1) + '\"></span>' +\r\n");
      out.write("                '<div class=\"info\">' +\r\n");
      out.write("                '   <h5>' + places.place_name + '</h5>';\r\n");
      out.write("\r\n");
      out.write("    if (places.road_address_name) {\r\n");
      out.write("        itemStr += '    <span>' + places.road_address_name + '</span>' +\r\n");
      out.write("                    '   <span class=\"jibun gray\">' +  places.address_name  + '</span>';\r\n");
      out.write("    } else {\r\n");
      out.write("        itemStr += '    <span>' +  places.address_name  + '</span>'; \r\n");
      out.write("    }\r\n");
      out.write("                 \r\n");
      out.write("      itemStr += '  <span class=\"tel\">' + places.phone  + '</span>' +\r\n");
      out.write("                '</div>';           \r\n");
      out.write("\r\n");
      out.write("    el.innerHTML = itemStr;\r\n");
      out.write("    el.className = 'item';\r\n");
      out.write("\r\n");
      out.write("    return el;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 마커를 생성하고 지도 위에 마커를 표시하는 함수입니다\r\n");
      out.write("function addMarker(position, idx, title) {\r\n");
      out.write("    var imageSrc = 'https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png', // 마커 이미지 url, 스프라이트 이미지를 씁니다\r\n");
      out.write("        imageSize = new kakao.maps.Size(36, 37),  // 마커 이미지의 크기\r\n");
      out.write("        imgOptions =  {\r\n");
      out.write("            spriteSize : new kakao.maps.Size(36, 691), // 스프라이트 이미지의 크기\r\n");
      out.write("            spriteOrigin : new kakao.maps.Point(0, (idx*46)+10), // 스프라이트 이미지 중 사용할 영역의 좌상단 좌표\r\n");
      out.write("            offset: new kakao.maps.Point(13, 37) // 마커 좌표에 일치시킬 이미지 내에서의 좌표\r\n");
      out.write("        },\r\n");
      out.write("        markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imgOptions),\r\n");
      out.write("            marker = new kakao.maps.Marker({\r\n");
      out.write("            position: position, // 마커의 위치\r\n");
      out.write("            image: markerImage \r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    marker.setMap(map); // 지도 위에 마커를 표출합니다\r\n");
      out.write("    markers.push(marker);  // 배열에 생성된 마커를 추가합니다\r\n");
      out.write("\r\n");
      out.write("    return marker;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 지도 위에 표시되고 있는 마커를 모두 제거합니다\r\n");
      out.write("function removeMarker() {\r\n");
      out.write("    for ( var i = 0; i < markers.length; i++ ) {\r\n");
      out.write("        markers[i].setMap(null);\r\n");
      out.write("    }   \r\n");
      out.write("    markers = [];\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 검색결과 목록 하단에 페이지번호를 표시는 함수입니다\r\n");
      out.write("function displayPagination(pagination) {\r\n");
      out.write("    var paginationEl = document.getElementById('pagination'),\r\n");
      out.write("        fragment = document.createDocumentFragment(),\r\n");
      out.write("        i; \r\n");
      out.write("\r\n");
      out.write("    // 기존에 추가된 페이지번호를 삭제합니다\r\n");
      out.write("    while (paginationEl.hasChildNodes()) {\r\n");
      out.write("        paginationEl.removeChild (paginationEl.lastChild);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    for (i=1; i<=pagination.last; i++) {\r\n");
      out.write("        var el = document.createElement('a');\r\n");
      out.write("        el.href = \"#\";\r\n");
      out.write("        el.innerHTML = i;\r\n");
      out.write("\r\n");
      out.write("        if (i===pagination.current) {\r\n");
      out.write("            el.className = 'on';\r\n");
      out.write("        } else {\r\n");
      out.write("            el.onclick = (function(i) {\r\n");
      out.write("                return function() {\r\n");
      out.write("                    pagination.gotoPage(i);\r\n");
      out.write("                }\r\n");
      out.write("            })(i);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        fragment.appendChild(el);\r\n");
      out.write("    }\r\n");
      out.write("    paginationEl.appendChild(fragment);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 검색결과 목록 또는 마커를 클릭했을 때 호출되는 함수입니다\r\n");
      out.write("// 인포윈도우에 장소명을 표시합니다\r\n");
      out.write("function displayInfowindow(marker, title) {\r\n");
      out.write("    var content = '<div style=\"padding:5px;z-index:1;\">' + title + '</div>';\r\n");
      out.write("\r\n");
      out.write("    infowindow.setContent(content);\r\n");
      out.write("    infowindow.open(map, marker);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" // 검색결과 목록의 자식 Element를 제거하는 함수입니다\r\n");
      out.write("function removeAllChildNods(el) {   \r\n");
      out.write("    while (el.hasChildNodes()) {\r\n");
      out.write("        el.removeChild (el.lastChild);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
